spring.application.name=ssafy_slap

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

weather.kma.service-key=${KMA_SERVICE_KEY:}
weather.kma.vilage-forecast-url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
